### ISSUE TITLE
npm install's pulling alot

### ISSUE THREAD

**Issue by xelawafs** [ireade/OfflineFX-Codelab#1]
npm install is pulling a lot from the registry. I had to abort with my folder now at 180 MB

**Comment by ireade** [comment]
Hey @xelawafs . Sorry about that. If it'll help you can remove the css stuff since you won't need to edit those. The css-related dependencies are -

- `postcss-scss`
- `gulp-sass`
- `gulp-postcss`
- `autoprefixer`

Don't forget to edit the gulpfile and remove the `css` task (also in the `default` and `watch` tasks).
